
server:
  port: 8080

spring:
  application:
    name: gateway-service

  sleuth:
    sampler:
      # 采样率的概率，100%采样
      probability: 1.0
      # 每秒采样数字最高为1000
      rate: 1000

  zipkin:
    base-url: ${ZIPKIN_URL:http://127.0.0.1:9411}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

resilience4j:
  ratelimiter:
    instances:
      productServiceRateLimiter:
        limitForPeriod: 1         # 每个时间段允许的请求数量
        limitRefreshPeriod: 1s     # 刷新限流器计数的时间间隔
        timeoutDuration: 50ms     # 请求等待进入限流器的超时时间
      orderServiceRateLimiter:
        limitForPeriod: 5          # 每个时间段允许的请求数量
        limitRefreshPeriod: 2s     # 刷新限流器计数的时间间隔
        timeoutDuration: 500ms     # 请求等待进入限流器的超时时间
      userServiceRateLimiter:
        limitForPeriod: 15         # 每个时间段允许的请求数量
        limitRefreshPeriod: 1s     # 刷新限流器计数的时间间隔
        timeoutDuration: 300ms     # 请求等待进入限流器的超时时间

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}   # Eureka Server 的地址
    register-with-eureka: true  # 是否将自己注册到Eureka服务器，默认为true
    fetch-registry: true  # 是否从Eureka服务器获取注册信息，默认为true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10  # 心跳间隔（默认 30 秒）
    lease-expiration-duration-in-seconds: 30  # 租约过期时间（默认 90 秒）