server:
  port: 8082

spring:
  application:
    name: user-service  # 微服务名称，Eureka 中展示的服务名

  cloud:
    config:
#      uri: ${CONFIG_SERVER_URL:http://127.0.0.1:8888}
      uri: ${CONFIG_SERVER_URL:http://config-server}
      fail-fast: true

  sleuth:
    sampler:
      # 采样率的概率，100%采样
      probability: 1.0
      # 每秒采样数字最高为1000
      rate: 1000

  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}

  redis:
    host: ${REDIS_URL:localhost}
    port: 6379

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      mode: always
      continue-on-error: false

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}   # Eureka Server 的地址
    register-with-eureka: true  # 是否将自己注册到Eureka服务器，默认为true
    fetch-registry: true  # 是否从Eureka服务器获取注册信息，默认为true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10  # 心跳间隔（默认 30 秒）
    lease-expiration-duration-in-seconds: 30  # 租约过期时间（默认 90 秒）

logging:
  level:
    root: INFO
    org.springframework.jdbc: DEBUG
    org.hibernate: DEBUG