spring:
  datasource:
    url: jdbc:h2:mem:testdb;
    driver-class-name: org.h2.Driver
    username: sa
    password: password

jwt:
  secret: 9cHxZR2NWhqV7K8vD4m3gT5bA6jF1sY0wL2nP9kM3cX7pJ4tQ8uE5hB1dN6fG # 使用Base64编码的256位随机密钥
  access-token:
    expiration: 30  # 30分钟
  refresh-token:
    expiration: 7   # 7天