server:
  port: 8081

spring:
  application:
    name: product-service  # 微服务名称，Eureka 中展示的服务名

  sleuth:
    sampler:
      # 采样率的概率，100%采样
      probability: 1.0
      # 每秒采样数字最高为1000
      rate: 1000

  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb;
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      mode: always
      continue-on-error: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}   # Eureka Server 的地址
    register-with-eureka: true  # 是否将自己注册到Eureka服务器，默认为true
    fetch-registry: true  # 是否从Eureka服务器获取注册信息，默认为true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10  # 心跳间隔（默认 30 秒）
    lease-expiration-duration-in-seconds: 30  # 租约过期时间（默认 90 秒）

logging:
  level:
    root: INFO
    org.springframework.jdbc: DEBUG
    org.hibernate: DEBUG

resilience4j:
  ratelimiter:
    instances:
      productServiceRateLimiter:
        limitForPeriod: 100        # 每个时间段允许的请求数量
        limitRefreshPeriod: 1s     # 刷新限流器计数的时间间隔
        timeoutDuration: 50ms     # 请求等待进入限流器的超时时间